### ISSUE TITLE
Black Screen when playing music from "Local Files"

### ISSUE THREAD

**Issue by realnajan** [Gabe-H/Gemini#12]
![Screenshot](https://user-images.githubusercontent.com/19735475/91608706-93de2780-e965-11ea-87b7-439462a3e9b0.png)

**Comment by kyleawayan** [comment]
I'm not sure how the Spotify API handles local files, since the music that you are playing does not come from Spotify. Note that this app doesn't connect with the local Spotify app on your computer, it uses the Spotify Web API
