### ISSUE TITLE
unable to open the app (macOS big sur)

### ISSUE THREAD

**Issue by rafasohhh** [Gabe-H/Gemini#36]
<img width="261" alt="Screenshot 2021-06-22 at 7 41 55 PM" src="https://user-images.githubusercontent.com/40794675/122918959-46b6c080-d392-11eb-89e8-af746c181de5.png">

**Comment by kyleawayan** [comment]
Looks like there may be an issue with the signing certificate. I am quite busy right now so I can take a look at it later.

For now you can try cloning the repository and building the app.

**Comment by kyleawayan** [comment]
@rafasohhh I no longer have an Apple signing certificate to sign this app as it costs annually. I will come back to this project when I have time.
