### ISSUE TITLE
brUh whY iS THERe NO dEsCrIpTiOn, WebsiTe, OR ToPIcs PrOVIDEd."??????????

### ISSUE THREAD

**Issue by kyleawayan** [Gabe-H/Gemini#7]
<img width="299" alt="Screen Shot 2020-08-26 at 9 00 49 AM" src="https://user-images.githubusercontent.com/56655579/91327735-caa41a00-e77a-11ea-8112-2695369f7879.png">

# It makes the repo look E M P T Y

<img width="454" alt="Screen Shot 2020-08-26 at 9 02 15 AM" src="https://user-images.githubusercontent.com/56655579/91327789-ddb6ea00-e77a-11ea-850a-684bc7fc1614.png">

**Comment by Gabe-H** [comment]
because i'VE NEVER LOOKED AT THAT BEFORE GOSHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

**Comment by kyleawayan** [comment]
h
